name: API Security Audit

on:
  schedule:
    - cron: 0 8 * * *

defaults:
  run:
    working-directory: api

jobs:
  audit:
    runs-on: ubuntu-latest
    name: API Security Audit

    steps:
      - name: Cloning repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Audit
        run: |
          make install
          poetry self add poetry-audit-plugin
          poetry audit
